# Generated by Django 4.1.1 on 2023-09-23 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="charteredOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carType", models.CharField(max_length=50)),
                ("chtdStartPrice", models.IntegerField(default=2000)),
                ("driverName", models.CharField(max_length=50)),
                ("driverPhone", models.CharField(max_length=10)),
                ("onOff", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="hailOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agencyName", models.CharField(max_length=50)),
                ("agencyNumber", models.CharField(max_length=10)),
                ("onOff", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="questProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quest_phone", models.CharField(max_length=10)),
                ("line_userId", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "quest_linename",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("lineid", models.CharField(blank=True, max_length=120, null=True)),
                ("order_times", models.PositiveIntegerField(default=0)),
                ("total_cost", models.IntegerField(default=0)),
                ("total_mileage", models.PositiveIntegerField(default=0)),
                (
                    "signUp_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={"ordering": ("-signUp_time",),},
        ),
        migrations.CreateModel(
            name="car_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("serviceType", models.CharField(max_length=20)),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("total_cost", models.IntegerField(default=0)),
                ("is_pay", models.BooleanField(default=False)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("be_canceled", models.BooleanField(default=False)),
                (
                    "quest_phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_order",
                        to="hailAndChartered.questprofile",
                    ),
                ),
            ],
            options={"ordering": ("-pub_datetime",),},
        ),
    ]
