# Generated by Django 4.1.1 on 2023-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hailAndChartered", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hailoption",
            name="agencyUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
