# Generated by Django 4.1.1 on 2023-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hailAndChartered", "0002_hailoption_agencyurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="charteredoption",
            name="carImgUrl",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hailoption",
            name="imgUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
