# Generated by Django 4.1.1 on 2023-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hailAndChartered", "0003_charteredoption_carimgurl_hailoption_imgurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hailoption",
            name="agencyNumber",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
