# Generated by Django 4.1.1 on 2023-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hailAndChartered", "0004_alter_hailoption_agencynumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="charteredoption",
            name="chtdAlldayPrice",
            field=models.IntegerField(default=4500),
        ),
        migrations.AddField(
            model_name="charteredoption",
            name="timeOutPrice",
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name="charteredoption",
            name="chtdStartPrice",
            field=models.IntegerField(default=3000),
        ),
    ]
