# Generated by Django 4.1.1 on 2023-09-27 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="qrcode_storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pwd", models.CharField(max_length=50)),
                (
                    "pub_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("limit_datetime", models.DateTimeField(blank=True, null=True)),
                ("finish_datetime", models.DateTimeField(blank=True, null=True)),
                ("main_userId", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "family_userId",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("be_canceled", models.BooleanField(default=True)),
            ],
            options={"ordering": ("-pub_datetime",),},
        ),
    ]
